/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "mmfdll.h"
/* Header for class com_nuror1_NuroCore */

#ifndef _Included_com_nuror1_NuroCore
#define _Included_com_nuror1_NuroCore
#ifdef __cplusplus
extern "C" {
#endif



JNIEXPORT jboolean Java_com_nuror1_NuroCore_setNuroPath
  (JNIEnv *env, jclass cls, jstring path);
    
    
/*
 * Class:     com_nuror1_NuroCore
 * Method:    setNuroBuffer
 * Signature: (Ljava/nio/ShortBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_setNuroBuffer
  (JNIEnv *, jclass, jobject, jint, jint);

JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_setNuroPicBuffer
  (JNIEnv *, jclass, jobject, jint, jint);


JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_setNuroEventMap
  (JNIEnv * env, jclass cls, jobject obj, jint nVal1);
/*
 * Class:     com_nuror1_NuroCore
 * Method:    injectEventMap
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_injectEventMap
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_nuror1_NuroCore
 * Method:    getFromEventMap
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_nuror1_NuroCore_getFromEventMap
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_nuror1_NuroCore
 * Method:    setToEventMap
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_nuror1_NuroCore_setToEventMap
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_nuror1_NuroCore
 * Method:    getPreparedAudio
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nuror1_NuroCore_getPreparedAudio
  (JNIEnv *, jclass);

/*
 * Class:     com_nuror1_NuroCore
 * Method:    setPreparedAudio
 * Signature: ()V
 */
JNIEXPORT void Java_com_nuror1_NuroCore_setPreparedAudio
    (JNIEnv * env, jclass cls);

    /*
 * Class:     com_nuror1_NuroCore
 * Method:    getVolume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nuror1_NuroCore_getVolume
  (JNIEnv *, jclass);

JNIEXPORT jboolean Java_com_nuror1_NuroCore_setVolume
  (JNIEnv * env, jclass cls,jint nVoice);

/*
 * Class:     com_nuror1_NuroCore
 * Method:    startNuro
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_startNuro
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_nuror1_NuroCore_stopNuro
  (JNIEnv *, jclass);

JNIEXPORT jboolean Java_com_nuror1_NuroCore_getNuroState
  (JNIEnv * env, jclass cls);

JNIEXPORT jboolean Java_com_nuror1_NuroCore_goPreDialog
  (JNIEnv *, jclass);

/*
 * Class:     com_nuror1_NuroCore
 * Method:    onMouseDown
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_onMouseDown
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_nuror1_NuroCore
 * Method:    onMouseUp
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_onMouseUp
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_nuror1_NuroCore
 * Method:    onMouseMove
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_onMouseMove
  (JNIEnv *, jclass, jint, jint);


JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_onKeyDown
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_nuro_r1_shlib_NuroCore
 * Method:    onMouseUp
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_onKeyUp
  (JNIEnv *, jclass, jint);
/*
 * Class:     com_nuror1_NuroCore
 * Method:    setGps
 * Signature: (Lcom/nuro/r1/shlib/NuroGpsStatus;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_setGps
  (JNIEnv *, jclass, jobject);

JNIEXPORT jboolean Java_com_nuror1_NuroCore_setGpsNema(JNIEnv * env, jclass cls, jstring GpsData,jboolean  bOK);

jint JNI_OnLoad(JavaVM *vm, void *reserved);
void JniUnLoad(JavaVM *vm, void *reserved);
//JNIEnv* GetEnv();


void Cal_NMEA_Chksum(char* str,char *chk);
bool LoadSo(int nMode,long nLat,long nLng,double nAngle,long nLatFix,long nLngFix,double nAngleFix);
bool MMF_MODFIFY(long in_x, long in_y,float in_angle, float AngularChange, long fCarSpeed, 
								float gps_angle, long gps_posX, long gps_posY);

JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_sendPoiStringUTF16BE
  (JNIEnv *, jclass, jbyteArray);

JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_keySound
  (JNIEnv *, jclass);

/*
 * Class:     com_nuror1_NuroCore
 * Method:    sendCopyData
 * Signature: (Lcom/nuror1/jCopyData;)V
 */
JNIEXPORT void JNICALL Java_com_nuror1_NuroCore_sendCopyData
  (JNIEnv *, jclass, jobject);

JNIEXPORT void JNICALL Java_com_nuror1_NuroCore_sendWindProc
  (JNIEnv *env, jclass cls, jlong, jlong, jlong);

JNIEXPORT jboolean Java_com_nuror1_NuroCore_GetTMCstate(JNIEnv *env, jclass cls);
JNIEXPORT jboolean Java_com_nuror1_NuroCore_SetTMCstate(JNIEnv *env, jclass cls,bool bTMC);
JNIEXPORT jstring Java_com_nuror1_NuroCore_getTMCMapName(JNIEnv *, jclass);

JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_SetSearchMode(JNIEnv *env, jclass cls, jint nMode);
JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_SetNameID(JNIEnv *env, jclass cls,jint nameID,jint nIdx);
JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_GetNameALL(JNIEnv *env, jclass cls,jint nType, jobject object);
JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_SetKey(JNIEnv *env, jclass cls,jint nType,jstring jstr);
JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_GetKeyBoard(JNIEnv *env, jclass cls,jint nameID, jobject object);
JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_GetListWord(JNIEnv *env, jclass cls,jint nType, jobject object);
JNIEXPORT jboolean JNICALL Java_com_nuror1_NuroCore_GetCandidateWord(JNIEnv *env, jclass cls,jint nType, jobject object);

//Hsin
JNIEXPORT void JNICALL Java_com_nuror1_NuroCore_DrawInfo(JNIEnv *env, jclass cls, jobject object);
JNIEXPORT void JNICALL Java_com_nuror1_NuroCore_GetUIConfig(JNIEnv *env, jclass cls, jobject object);
JNIEXPORT void JNICALL Java_com_nuror1_NuroCore_TransferCoordinate(JNIEnv *env, jclass cls, jint nDef, jint nX, jint nY, jobject object);
JNIEXPORT void JNICALL Java_com_nuror1_NuroCore_GetNaviList(JNIEnv *env, jclass cls, jint GetIndex, jint Get_List_On_Page);
JNIEXPORT void JNICALL Java_com_nuror1_NuroCore_GetTmcPathData(JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_nuror1_NuroCore_MouseEvent(JNIEnv *env, jclass cls, jobject object);
#ifdef __cplusplus
}
#endif
#endif
